service: csharpSort

provider:
  name: aws
  runtime: dotnetcore1.0
  memorySize: ${env:FUNC_MEMORY}
  timeout: ${env:FUNC_TIMEOUT}

package:
  artifact: artifact/package.zip

functions:
  hello:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::Hello
    events:
        - http:
            path: hello
            method: GET
            cors: true
        - cloudwatchLog:
            filter: ${env:FUNC_FILTER}