service: nodejsSort

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: ${env:FUNC_MEMORY}
  timeout: ${env:FUNC_TIMEOUT}

functions:
  hello:
    handler: handler.hello
    events:
        - http: GET hello
        - cloudwatchLog:
            logGroup: /nodejsSort
            filter: ${env:FUNC_FILTER}